package org.pattonvillerobotics.team2866.robotclasses.controller;

/**
 * Created by skaggsm on 1/7/16.
 */
public enum GamepadFeature {
    GAMEPAD_1_BUTTON_X, GAMEPAD_1_BUTTON_Y, GAMEPAD_1_BUTTON_A, GAMEPAD_1_BUTTON_B,
    GAMEPAD_1_DPAD_UP, GAMEPAD_1_DPAD_DOWN, GAMEPAD_1_DPAD_LEFT, GAMEPAD_1_DPAD_RIGHT,
    GAMEPAD_1_TRIGGER_LEFT, GAMEPAD_1_TRIGGER_RIGHT,
    GAMEPAD_1_BUMPER_LEFT, GAMEPAD_1_BUMPER_RIGHT,
    GAMEPAD_1_STICK_LEFT_X, GAMEPAD_1_STICK_LEFT_Y, GAMEPAD_1_STICK_RIGHT_X, GAMEPAD_1_STICK_RIGHT_Y,

    GAMEPAD_2_BUTTON_X, GAMEPAD_2_BUTTON_Y, GAMEPAD_2_BUTTON_A, GAMEPAD_2_BUTTON_B,
    GAMEPAD_2_DPAD_UP, GAMEPAD_2_DPAD_DOWN, GAMEPAD_2_DPAD_LEFT, GAMEPAD_2_DPAD_RIGHT,
    GAMEPAD_2_TRIGGER_LEFT, GAMEPAD_2_TRIGGER_RIGHT,
    GAMEPAD_2_BUMPER_LEFT, GAMEPAD_2_BUMPER_RIGHT,
    GAMEPAD_2_STICK_LEFT_X, GAMEPAD_2_STICK_LEFT_Y, GAMEPAD_2_STICK_RIGHT_X, GAMEPAD_2_STICK_RIGHT_Y
}
